# Site settings
title: ""
simple_search: http://google.com/search
email: v.deepakraya@gmail.com
description: "By Deepak Raya"
baseurl: ""
url: "https://deepakraya.github.io"
twitter_username: VDeepakRaya
github_username: DeepakRaya

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
